### PR TITLE
.net core and f#

### PR DESCRIPTION
**Pull request by wallymathieu**
```c#
    using LogError = Action<string, Exception>;
    using LogDebug = Action<string>;
```
While the previous definition was to c# centric and slightly hacky to use:
```c#
    public delegate void LoggerDelegate(Exception exception = null,
        object fields = null,
        string fatal = null,
        string error = null,
        string warn = null,
        string debug = null,
        string info = null);
```

### CODE REVIEW

**Comment by wallymathieu** [comment]
What do you think @haf ?

**Comment by haf** [comment]
@wallymathieu I'm sure your improvements are really good, but as you know I disagree with the premise of allowing you to plug in a "random logging framework". After all, I wrote Logary so there would exist "the best logging and metrics and tracing framework for .net apps", not to work around deficiencies in other frameworks that I have no control of.

If you want my take on your code, it's https://github.com/logary/logary/blob/master/src/Logary.CSharp.Facade/Facade.cs — the only thing you have to adapt is the data structure https://github.com/logary/logary/blob/master/src/Logary.CSharp.Facade/Facade.cs#L129 and you'll have support for *any* framework with the Facade.cs. Hence; you writing 

> (Logary assumes that you want to use Logary as an adapter)

is [not fully accurate](https://www.nuget.org/packages/Suave.SerilogExtensions/).

That said, thanks for adding Logary support and keep up the good work.

**Comment by haf** [comment]
BTW; if you actively work on a Facade (and use it in prod) for C# that other logging frameworks plug into, I'd be delighted to work with you on the Logary facade (c#'s facade needs upgrading to v3->v4); you could keep your adapters in that project too. The Facades will always be Apache 2.0 licensed. ...but I don't have the bandwidth to comment much on overlapping projects that don't bring my own projects/aims forward.

**Comment by wallymathieu** [comment]
Thanks for the doc review! I've removed the comment.

The intention here is to provide a minimal thing you drop into a library in order to have minimal logging in a simple way that you later on can plug in "random logging framework". I don't like having to tie libraries to specific logging abstractions. The API is intended to be as small as possible to make it easy to implement and use. In f# you'd implement it as:
```
module internal Logger=
    /// Log level
    type Level=
        |Debug = 0
        |Info = 1
        |Warn = 2
        |Error = 3
    type LogMessage = int * string * exn * obj
    type Logger = LogMessage -> unit
    ...    
```

Though in hindsight it's perhaps not good enough due to `int` being too diffuse.

**Comment by haf** [comment]
@wallymathieu But you're designing a specific logging abstraction here, are you not? Also, who says your logging framework takes input synchronously and without side-effects? What happens if your library wants an ACK back? What thread does the consumer run on? What is your synchronisation context? Can you read thread-static memory at the call-site?

**Comment by wallymathieu** [comment]
Yes, the type of logging use is when you send out logs without expecting an ACK back. What kind of library code expects the logging framework to provide an ACK? I can understand it if you have a business app, where you want to make sure that metrics et.c. get sent.

I previously used:
```c#
    public delegate void LoggerDelegate(Exception exception = null,
        object fields = null,
        string fatal = null,
        string error = null,
        string warn = null,
        string debug = null,
        string info = null);
``` 
for some c# projects. Though the downside has been that it's too c# focused and too dependent on named optional parameters (so not as portable as one would wish).

For Carable we have used:
```c#
internal delegate void OnError(string message, System.Exception exception = null);
```
and `Microsoft.Extensions.Logging` for libraries. I'm somewhat skeptical of the use of the Microsoft base libraries in libraries as they make the libraries harder to use from other context (c# scripting, f# et.c.).

**Comment by wallymathieu** [comment]
So the design of this logging abstraction is to fit the use case when you want to inject in logging to a library without tying the library to specific abstractions.

**Comment by wallymathieu** [comment]
> but I don't have the bandwidth to comment much on overlapping projects that don't bring my own projects/aims forward.

Why I appreciate the input!

**Comment by haf** [comment]
> What kind of library code expects the logging framework to provide an ACK?

E.g. Fatal/Critical logs, before crashing. I have that in a few places. When I wrote code for RayStation, we'd crash if the log level was critical, and that absolutely had to be acked, as written to disk. But your ability to block and ack without deadlocks depend on your synchronisation context.

Nowadays I write all my code in a batching parallel manner; that means we'll have 10-20 threads independently running at any point in time. You have to define what logging means then, as well.

So I'm afraid that a virtual machine specification, like what CoreCLR gives you, is what you have to work with. Just because you ignore your synchronisation context, doesn't mean it's not there.

**Comment by wallymathieu** [comment]
Thanks! That makes it much clearer why you'd want that type of behavior.

**Comment by haf** [comment]
In the end you'll have written a logging abstraction.

From what I understand from talking to you, you dislike my Facade because:

 - it returns a [Task](https://github.com/logary/logary/blob/master/src/Logary.CSharp.Facade/Facade.cs#L217), which is a type-level representation of your synchronisation context (or a handoff to another)
 - the Message type is too large, hence more of "an abstraction", in your parlour?

**Comment by wallymathieu** [comment]
I think Logary Facade has it's place. I **don't** dislike it. I'd imagine I could use it in some future service code (though lately I've coded mostly in c# at work). 

The kind of logging that I want to inject into simple libraries is usually in order to be able to inject simple logging that does not crash (i.e. that potentially sends the message to a separate thread without waiting for an ACK). If something really goes wrong it should throw an exception and you'd log the exception. That implies that you have a certain type of logging and certain type of library.

So you are right in that for that style of libraries I want the abstraction to be minimal.

**Comment by haf** [comment]
Thanks for expanding on your thoughts.

> I'd imagine I could use it in some future service code (though lately I've coded mostly in c# at work).

You're aware that there's one in C#?

**Comment by wallymathieu** [comment]
I'm aware of it. The biggest reason has been that we have mostly written asp.net core mvc style apps: drinking the cool aid (logging, dependency injection, configuration).

**Pull request merged**
